build:
  maxIssues: 0

complexity:
  LargeClass:
    excludes: ['**/test/**']
  LongParameterList:
    ignoreDefaultParameters: true
    ignoreAnnotated: ['Inject']
  TooManyFunctions:
    active: false

formatting:
  active: true
  autoCorrect: true
  Indentation:
    active: true
    autoCorrect: true

style:
  UnnecessaryAbstractClass:
    active: true
    ignoreAnnotated: [ 'Module' ]

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]

